name: flutter_ecom
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  cached_network_image: ^3.3.0
  flutter:
    sdk: flutter
  flutter_rating_bar: ^4.0.1
  flutter_slidable: ^3.0.1
  flutter_staggered_grid_view: ^0.4.0
  font_awesome_flutter: ^10.6.0
  google_fonts: ^6.1.0
  hive_flutter: ^1.1.0
  ionicons: ^0.2.2
  provider: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/json/
    - assets/images/
